modLoader="javafml"
loaderVersion="43.4.0"
license="MIT License"

[[mods]]
modId="antimatteraddon"
version="0.0.1"
displayName="antimatteraddon"
authors="arsen"
description='''an addon for ic2c'''

[[dependencies]]
modId="forge"
mandatory=true
versionRange="43.4.0"
ordering="NONE"
side="BOTH"

[[dependencies]]
modId="minecraft"
mandatory=true
versionRange="1.19.2"
ordering="NONE"
side="BOTH"
